PORTNAME=	xf86-input-elographics
PORTVERSION=	1.4.2
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre elographics input driver
WWW=		https://github.com/X11Libre/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GH_TAGNAME=	80ef66f
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
