PORTNAME=	xf86-video-ast
PORTVERSION=	1.1.5
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre ASPEED display driver
WWW=		https://github.com/X11Libre/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GH_TAGNAME=	e86afcc
USES=		xlibre-cat:driver
INSTALL_TARGET=	install-strip

PLIST_FILES=	lib/xorg/modules/drivers/ast_drv.so

.include <bsd.port.mk>
