PORTNAME=	xf86-input-keyboard
PORTVERSION=	1.9.0
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre keyboard input driver
WWW=		https://github.com/X11Libre/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GH_TAGNAME=	08eb4fd
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
