PORTNAME=	xf86-video-nv
PORTVERSION=	2.1.22
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre nv display driver
WWW=		https://github.com/X11Libre/

GH_TAGNAME=	526f800
GH_ACCOUNT=	b-aaz
USES=		tar:xz xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
