PORTNAME=	xf86-input-void
PORTVERSION=	1.4.1
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre void input driver
WWW=		https://github.com/X11Libre/

GH_TAGNAME=	b43e11e
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
