PORTNAME=	xlibre-xf86-input-mouse
PORTVERSION=	1.9.3
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre mouse input driver
WWW=		https://github.com/X11Libre/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GH_TAGNAME=	a0aa387
USES=		pathfix xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
