PORTNAME=	xlibre-xf86-video-mga
PORTVERSION=	2.0.0
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre mga display driver
WWW=		https://github.com/X11Libre/

GH_TAGNAME=	3f2000a
USES=		gl xlibre-cat:driver
USE_GL=		gl

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
