PORTNAME=	xlibre-xf86-input-joystick
PORTVERSION=	1.6.3
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre joystick input driver
WWW=		https://github.com/X11Libre/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GH_TAGNAME=	f6e29f8
USES=		pathfix xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
