PORTNAME=	xf86-video-vesa
PORTVERSION=	2.5.0
PORTREVISION=	3
CATEGORIES=	x11-drivers
WWW=		https://githhub.com/X11Libre

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre vesa display driver

GH_TAGNAME=	5b33e95
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
