PORTNAME=	xlibre-xf86-video-dummy
PORTVERSION=	0.3.8
PORTREVISION=	4
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre dummy display driver
WWW=		https://github.com/X11Libre/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GH_TAGNAME=	3a407a3
USES=		xlibre-cat:driver

.include <bsd.port.mk>
